# Generated by Django 5.2.8 on 2025-11-22 22:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.JSONField(blank=True, default=list)),
                ('model_type', models.CharField(choices=[('local', 'Local'), ('api', 'API')], default='local', max_length=10)),
                ('model_name', models.CharField(default='gpt-4o-mini', max_length=120)),
                ('preprompt', models.TextField(blank=True)),
                ('description', models.CharField(max_length=250)),
                ('avatar', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='agent_pics/')),
                ('is_public', models.BooleanField(default=True)),
                ('cooldown', models.PositiveIntegerField(default=5)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
