# Generated by Django 5.2.8 on 2025-11-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='user_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
