# Generated by Django 5.2.8 on 2025-11-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_agent_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='model_name',
            field=models.CharField(choices=[('local', 'Local'), ('api', 'API')], default='gpt-4o-mini', max_length=120),
        ),
    ]
