# Generated by Django 5.2.8 on 2025-12-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_agent_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='model_name',
            field=models.CharField(choices=[('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4o', 'GPT-4o'), ('o3-mini', 'O3 Mini'), ('llama3:8b', 'LLaMA 3 8B'), ('qwen2.5:3b', 'Qwen 2.5 3B')], default='gpt-4o-mini', max_length=120),
        ),
        migrations.AlterField(
            model_name='agent',
            name='model_type',
            field=models.CharField(choices=[('local', 'Local'), ('api', 'API')], default='api', max_length=10),
        ),
    ]
