# Generated by Django 5.2.8 on 2025-12-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_agent_model_name_alter_agent_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='is_public',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='agent',
            name='model_name',
            field=models.CharField(choices=[('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4o', 'GPT-4o'), ('o3-mini', 'O3 Mini'), ('distilgpt2', 'DistilGPT2 (Local - Léger)'), ('gpt2', 'GPT2 (Local - Moyen)')], default='gpt-4o-mini', max_length=120),
        ),
    ]
