# Generated by Django 5.2.8 on 2025-12-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_agent_is_public_alter_agent_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='message_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agent',
            name='model_name',
            field=models.CharField(choices=[('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4o', 'GPT-4o'), ('o3-mini', 'O3 Mini'), ('SmolLm-135M', 'Smol LM 135M')], default='gpt-4o-mini', max_length=120),
        ),
    ]
