# Generated by Django 5.2.8 on 2025-12-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_agent_message_count_alter_agent_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='model_name',
            field=models.CharField(choices=[('gpt-4o-mini', 'GPT-4o Mini'), ('SmolLm-135M', 'Smol LM 135M')], default='gpt-4o-mini', max_length=120),
        ),
    ]
